// prettier.config.js
module.exports = {
	bracketSpacing: true,
	semi: true,
	printWidth: 50,
	tabWidth: 1,
	trailingComma: "es5",
	useTabs: true,
	singleQuote: false,
	arrowParens: "always",
	importOrderSeparation: false,
	importOrderSortSpecifiers: true,
	tailwindConfig: "./tailwind.config.js",
	importOrder: [
		"^(next/(.*)$)|^(next$)",
		"^(react/(.*)$)|^(react$)",
		"^<THIRD_PARTY_MODULES>",
		"",
		"^@/(.*)$",
		"^[./]",
	],
	importOrderSeparation: false,
	importOrderSortSpecifiers: true,
	importOrderBuiltinModulesToTop: true,
	importOrderParserPlugins: [
		"typescript",
		"jsx",
		"decorators-legacy",
	],
	importOrderMergeDuplicateImports: true,
	importOrderCombineTypeAndValueImports: true,
	plugins: [
		require("prettier-plugin-tailwindcss"),
		"@ianvs/prettier-plugin-sort-imports",
	],
};
