import SiteNav from "@/components/site-hav";
import "./globals.css";
import SiteFooter from "@/components/site-footer";

export const metadata = {
	title: "Nazhoir",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang="en"
			className="bg-stone-950 text-stone-300"
		>
			<body className="mx-auto max-w-2xl pt-40">
				<SiteNav />
				{children}
				<SiteFooter />
			</body>
		</html>
	);
}
